# Generated by Django 6.0.6 on 2026-07-11 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='نام')),
                ('image', models.ImageField(blank=True, upload_to='actors/', verbose_name='تصویر')),
            ],
            options={
                'verbose_name': 'بازیگر',
                'verbose_name_plural': 'بازیگران',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام')),
                ('code', models.CharField(max_length=3, unique=True, verbose_name='کد')),
            ],
            options={
                'verbose_name': 'کشور',
                'verbose_name_plural': 'کشورها',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='نام')),
                ('image', models.ImageField(blank=True, upload_to='directors/', verbose_name='تصویر')),
            ],
            options={
                'verbose_name': 'کارگردان',
                'verbose_name_plural': 'کارگردان\u200cها',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='نام')),
                ('slug', models.SlugField(unique=True, verbose_name='اسلاگ')),
            ],
            options={
                'verbose_name': 'ژانر',
                'verbose_name_plural': 'ژانرها',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('original_title', models.CharField(blank=True, max_length=255, verbose_name='عنوان اصلی')),
                ('persian_title', models.CharField(blank=True, max_length=255, verbose_name='عنوان فارسی')),
                ('slug', models.SlugField(unique=True)),
                ('media_type', models.CharField(choices=[('movie', 'فیلم'), ('series', 'سریال'), ('anime', 'انیمه'), ('animation', 'انیمیشن')], max_length=20, verbose_name='نوع')),
                ('status', models.CharField(choices=[('released', 'منتشر شده'), ('upcoming', 'به زودی'), ('ended', 'پایان یافته'), ('canceled', 'لغو شده')], default='released', max_length=20, verbose_name='وضعیت')),
                ('overview', models.TextField(blank=True, verbose_name='خلاصه')),
                ('release_date', models.DateField(blank=True, null=True, verbose_name='تاریخ انتشار')),
                ('runtime', models.PositiveIntegerField(blank=True, null=True, verbose_name='مدت زمان (دقیقه)')),
                ('imdb_rating', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='امتیاز IMDb')),
                ('poster', models.ImageField(blank=True, upload_to='media/posters/', verbose_name='پوستر')),
                ('backdrop', models.ImageField(blank=True, upload_to='media/backdrops/', verbose_name='بک\u200cدراپ')),
                ('trailer', models.URLField(blank=True, verbose_name='لینک تریلر')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('actors', models.ManyToManyField(blank=True, to='media_library.actor', verbose_name='بازیگران')),
                ('countries', models.ManyToManyField(blank=True, to='media_library.country', verbose_name='کشورها')),
                ('directors', models.ManyToManyField(blank=True, to='media_library.director', verbose_name='کارگردان\u200cها')),
                ('genres', models.ManyToManyField(blank=True, to='media_library.genre', verbose_name='ژانرها')),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season_number', models.PositiveIntegerField(verbose_name='شماره فصل')),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasons', to='media_library.media', verbose_name='رسانه')),
            ],
            options={
                'verbose_name': 'فصل',
                'verbose_name_plural': 'فصل\u200cها',
                'ordering': ['season_number'],
                'unique_together': {('media', 'season_number')},
            },
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('episode_number', models.PositiveIntegerField(verbose_name='شماره قسمت')),
                ('runtime', models.PositiveIntegerField(blank=True, null=True, verbose_name='مدت زمان (دقیقه)')),
                ('release_date', models.DateField(blank=True, null=True, verbose_name='تاریخ انتشار')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='media_library.season', verbose_name='فصل')),
            ],
            options={
                'verbose_name': 'قسمت',
                'verbose_name_plural': 'قسمت\u200cها',
                'ordering': ['episode_number'],
                'unique_together': {('season', 'episode_number')},
            },
        ),
    ]
