# Generated by Django 6.0.6 on 2026-07-11 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_library', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='پیشنهاد ویژه'),
        ),
    ]
