# Generated by Django 6.0.6 on 2026-07-16 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_library', '0002_media_is_featured'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان منبع')),
                ('quality', models.CharField(choices=[('480p', '480p'), ('720p', '720p'), ('1080p', '1080p'), ('2160p', '2160p (4K)')], default='1080p', max_length=20, verbose_name='کیفیت')),
                ('language', models.CharField(choices=[('dubbed', 'دوبله'), ('subtitle', 'زیرنویس')], default='subtitle', max_length=20, verbose_name='زبان')),
                ('subtitle_language', models.CharField(blank=True, max_length=50, null=True, verbose_name='زبان زیرنویس')),
                ('source_type', models.CharField(choices=[('stream', 'پخش آنلاین'), ('download', 'دانلود مستقیم')], default='download', max_length=20, verbose_name='نوع منبع')),
                ('url', models.URLField(max_length=1000, verbose_name='آدرس URL')),
                ('file_size', models.CharField(blank=True, max_length=50, null=True, verbose_name='حجم فایل')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('ordering', models.IntegerField(default=0, verbose_name='ترتیب')),
                ('episode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='media_library.episode', verbose_name='قسمت')),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='media_library.media', verbose_name='رسانه')),
            ],
            options={
                'verbose_name': 'منبع رسانه',
                'verbose_name_plural': 'منابع رسانه\u200cها',
                'ordering': ['ordering', 'id'],
            },
        ),
    ]
